/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import baseDatos.Conexion;
import baseDatos.OperacionesTabla;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.Accion;
import modelo.Caso;
import modelo.MiModeloTabla;
import modelo.Usuario;

/**
 *
 * @author Yesica
 */
public class PnlConsultaCasosAbogado extends javax.swing.JPanel {

    DefaultComboBoxModel modeloCombo;
    Conexion conexion;
    OperacionesTabla operaciones;
    MiModeloTabla modeloTablaCasos;
    MiModeloTabla modeloTablaAcciones;

    /**
     * Creates new form PnlConsultaCasosAbogado
     */
    public PnlConsultaCasosAbogado() {
        initComponents();
        conexion = new Conexion();

        if (conexion.establecer("jdbc:mysql://localhost:3306/bufetemachor") == -1) {
            JOptionPane.showMessageDialog(null, "Errores en la base de datos");
            System.exit(-1);
        } else {
            operaciones = new OperacionesTabla(conexion);
        }
        modeloCombo = new DefaultComboBoxModel();//creamos el modeloCombo de los datos
        cmbAbogados.setModel(modeloCombo);//insertamos los datos
        cargarInfoCombo();
        modeloTablaCasos = new MiModeloTabla();
        String[] titulos = {"Código caso", "Titulo"};//titulos de las columnas de la tabla
        modeloTablaCasos.setColumnIdentifiers(titulos);//inserta los titulos escritos
        tblCasos.setModel(modeloTablaCasos);
        modeloTablaAcciones = new MiModeloTabla();
        String[] titulosAcciones = {"Código acción", "Fecha", "Descripción"};
        modeloTablaAcciones.setColumnIdentifiers(titulosAcciones);//inserta los titulos escritos 
        tblAcciones.setModel(modeloTablaAcciones);
    }

    /**
     * carga la lista de abogados en el combo
     */
    private void cargarInfoCombo() {
        modeloCombo.addElement("Seleccione una opción");//sale como primera opcion la frase
        ArrayList<Usuario> usuarios = operaciones.todosUsuarios();
        modeloCombo.addAll(usuarios);

    }

    /**
     * carga los casos abiertos del abogado seleccionado
     * @param dni 
     */
    private void cargarTablaCasos(String dni) {
        limpiarTablaCasos();
        ArrayList<Caso> casos;
        casos = operaciones.buscarCasos(dni);
        for (Caso c : casos) {
            Vector v = new Vector();
            v.add(c);
            v.add(c.getTitulo());
            modeloTablaCasos.addRow(v);
        }
    }

    
    /**
     * carga las acciones del caso seleccionado
     * @param codCaso 
     */
    private void cargarTablaAcciones(String codCaso) {
        limpiarTablaAcciones();
        ArrayList<Accion> acciones = operaciones.buscarAcciones(codCaso);
        for (Accion a : acciones) {
            Vector v = new Vector();
            v.add(a.getCodAccion());
            v.add(a.getFecha());
            v.add(a.getDescripcion());
            modeloTablaAcciones.addRow(v);
        }
    }

    /**
     * borra los datos cargados en la tabla de casos
     */
    private void limpiarTablaCasos() {
        int nFilas = modeloTablaCasos.getRowCount();
        for (int pos = 0; pos < nFilas; pos++) {
            modeloTablaCasos.removeRow(0);
        }
    }

    /**
     * borra las acciones cargadas en la tabla de acciones
     */
    private void limpiarTablaAcciones() {
        int nFilas = modeloTablaAcciones.getRowCount();
        for (int pos = 0; pos < nFilas; pos++) {
            modeloTablaAcciones.removeRow(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbAbogados = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAcciones = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCasos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbAbogados.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        cmbAbogados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbAbogados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAbogadosActionPerformed(evt);
            }
        });
        add(cmbAbogados, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 220, 40));

        txtDescripcion.setEditable(false);
        txtDescripcion.setColumns(20);
        txtDescripcion.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        txtDescripcion.setRows(5);
        jScrollPane3.setViewportView(txtDescripcion);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 470, 90));

        tblAcciones.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        tblAcciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblAcciones);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 470, 110));

        tblCasos.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        tblCasos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCasos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCasosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCasos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 470, 100));

        jLabel1.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Consulta casos por abogados");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAbogadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAbogadosActionPerformed
        int pos = cmbAbogados.getSelectedIndex();//dame el seleccionado
        if (pos != 0) {
            String dni;
            Usuario usuario = (Usuario) cmbAbogados.getSelectedItem();
            dni = usuario.getDni();
            cargarTablaCasos(dni);
            limpiarTablaAcciones();
            txtDescripcion.setText("");
        } else {
            try {
                limpiarTablaCasos();
                limpiarTablaAcciones();
                txtDescripcion.setText("");

            } catch (Exception ex) {

            }
        }
    }//GEN-LAST:event_cmbAbogadosActionPerformed

    private void tblCasosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCasosMouseClicked
        Caso seleccionado;
        String codCaso;
        int fila = tblCasos.rowAtPoint(evt.getPoint());
        // int columna = tabla.columnAtPoint(e.getPoint()); no me interesa la columna ha pulsado
        if ((fila > -1) /*&& (columna > -1)*/) {

            seleccionado = (Caso) modeloTablaCasos.getValueAt(fila, 0);//me devuelve el valor que exite en la fila que se ha hecho clic, columna 0
            codCaso = seleccionado.getCodigo();
            txtDescripcion.setText(seleccionado.getDescripcion());
            cargarTablaAcciones(codCaso);
        }
    }//GEN-LAST:event_tblCasosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbAbogados;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblAcciones;
    private javax.swing.JTable tblCasos;
    private javax.swing.JTextArea txtDescripcion;
    // End of variables declaration//GEN-END:variables
}
