/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import baseDatos.Conexion;
import baseDatos.OperacionesTabla;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.Accion;
import modelo.Caso;
import modelo.MiModeloTabla;
import utilidades.Fecha;

/**
 *
 * @author Yesica
 */
public class PnlCierreCaso extends javax.swing.JPanel {

    DefaultComboBoxModel modeloCombo;
    Conexion conexion;
    OperacionesTabla operaciones;
    MiModeloTabla modeloTablaAcciones;

    /**
     * Creates new form PnlCierreCaso
     */
    public PnlCierreCaso() {
        initComponents();
        conexion = new Conexion();

        if (conexion.establecer("jdbc:mysql://localhost:3306/bufetemachor") == -1) {
            JOptionPane.showMessageDialog(null, "Errores en la base de datos");
            System.exit(-1);
        } else {
            operaciones = new OperacionesTabla(conexion);
        }
        modeloCombo = new DefaultComboBoxModel();//creamos el modeloCombo de los datos
        cmbCasos.setModel(modeloCombo);//insertamos los datos
        cargarInfoCombo();
        modeloTablaAcciones = new MiModeloTabla();
        String[] titulosAcciones = {"Código acción", "Fecha", "Descripción"};
        modeloTablaAcciones.setColumnIdentifiers(titulosAcciones);//inserta los titulos escritos 
        tblAcciones.setModel(modeloTablaAcciones);
        btnCerrar.setEnabled(false);
    }

    private void cargarInfoCombo() {
        modeloCombo.addElement("Seleccione una opción");//sale como primera opcion la frase
        ArrayList<Caso> casos = operaciones.todosCasos();
        modeloCombo.addAll(casos);

    }

    private void cargarTablaAcciones(String codCaso) {
        limpiarTablaAcciones();
        ArrayList<Accion> acciones = operaciones.buscarAcciones(codCaso);
        for (Accion a : acciones) {
            Vector v = new Vector();
            v.add(a.getCodAccion());
            v.add(a.getFecha());
            v.add(a.getDescripcion());
            modeloTablaAcciones.addRow(v);
        }
    }

    private void limpiarTablaAcciones() {
        int nFilas = modeloTablaAcciones.getRowCount();
        for (int pos = 0; pos < nFilas; pos++) {
            modeloTablaAcciones.removeRow(0);
        }
    }

    private void limpiar() {
        limpiarTablaAcciones();
        cmbCasos.setSelectedIndex(0);
        txtDescripcion.setText("");
        lblDni.setText("");
        lblTitulo.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDni = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAcciones = new javax.swing.JTable();
        cmbCasos = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDni.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        lblDni.setForeground(new java.awt.Color(255, 255, 255));
        add(lblDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 160, 20));

        lblTitulo.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 120, 20));

        btnCerrar.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        btnCerrar.setText("Cerrar caso");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, -1, -1));

        btnCancelar.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, -1, -1));

        txtDescripcion.setEditable(false);
        txtDescripcion.setColumns(20);
        txtDescripcion.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 340, 110));

        tblAcciones.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        tblAcciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblAcciones);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, 110));

        cmbCasos.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        cmbCasos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCasos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCasosActionPerformed(evt);
            }
        });
        add(cmbCasos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 230, 50));

        jLabel3.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Letrado:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, 20));

        jLabel2.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Caso:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, 20));

        jLabel1.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cierre de casos");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCasosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCasosActionPerformed
        int pos = cmbCasos.getSelectedIndex();//dame el seleccionado
        if (pos != 0) {
            //limpiarTablaAcciones();            
            String codigo;
            Caso caso = (Caso) cmbCasos.getSelectedItem();
            codigo = caso.getCodigo();
            cargarTablaAcciones(codigo);
            txtDescripcion.setText(caso.getDescripcion());
            lblDni.setText(caso.getDni());
            lblTitulo.setText(caso.getTitulo());
            btnCerrar.setEnabled(true);
        } else {
            btnCerrar.setEnabled(false);
            try {
                limpiar();
            } catch (Exception ex) {

            }
        }
    }//GEN-LAST:event_cmbCasosActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        int pos = cmbCasos.getSelectedIndex();
        String codigo;
        Caso caso = (Caso) cmbCasos.getSelectedItem();
        codigo = caso.getCodigo();
        operaciones.cerrarCaso(codigo);
        JOptionPane.showMessageDialog(this, "Caso cerrado", "Información", JOptionPane.INFORMATION_MESSAGE);
        String codAccion = "CER";
        String fecha = Fecha.fechaActualNumero();
        String descripcionAccion = "Cierre del caso";
        operaciones.crearAccion(codigo, codAccion, fecha, descripcionAccion);
        limpiar();

        cmbCasos.removeItemAt(pos);

    }//GEN-LAST:event_btnCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JComboBox<String> cmbCasos;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblAcciones;
    private javax.swing.JTextArea txtDescripcion;
    // End of variables declaration//GEN-END:variables
}
