/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import baseDatos.Conexion;
import baseDatos.OperacionesTabla;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.Usuario;
import utilidades.Fecha;

/**
 *
 * @author Yesica
 */
public class PnlNuevosCasos extends javax.swing.JPanel {

    DefaultComboBoxModel modeloCombo;
    Conexion conexion;
    OperacionesTabla operaciones;

    /**
     * Creates new form PnlNuevosCasos
     */
    public PnlNuevosCasos() {
        initComponents();
        conexion = new Conexion();

        if (conexion.establecer("jdbc:mysql://localhost:3306/bufetemachor") == -1) {
            JOptionPane.showMessageDialog(null, "Errores en la base de datos");
            System.exit(-1);
        } else {
            operaciones = new OperacionesTabla(conexion);
        }
        modeloCombo = new DefaultComboBoxModel();//creamos el modeloCombo de los datos
        cmbAbogados.setModel(modeloCombo);//insertamos los datos
        cargarInfoCombo();
        //lblFecha.setText(Fecha.fechaActual());
        //lblSituacion.setText("ABIERTO");
    }

    private void cargarInfoCombo() {
        modeloCombo.addElement("Seleccione una opción");//sale como primera opcion la frase
        ArrayList<Usuario> usuarios = operaciones.todosUsuarios();
        modeloCombo.addAll(usuarios);
        // modeloCombo.setSelectedIndex(0);
    }

    private void limpiar() {
        txtCodigo.setText("");
        txtDescripcion.setText("");
        txtTitulo.setText("");
        cmbAbogados.setSelectedIndex(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbAbogados = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        txtCodigo = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Abogado");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, 20));

        jLabel4.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Título caso");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Descripción");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jLabel2.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Código");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jLabel1.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nuevos casos");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        cmbAbogados.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        cmbAbogados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbAbogados, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 210, 30));

        txtDescripcion.setColumns(20);
        txtDescripcion.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 290, 160));

        txtCodigo.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 210, 30));

        txtTitulo.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 210, 30));

        btnCancelar.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, -1, -1));

        btnAceptar.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String titulo;
        String codigo;
        String descripcion;
        // String fecha;
        String situacion;
        String dni;
        titulo = txtTitulo.getText();
        codigo = txtCodigo.getText();
        situacion = "a";
        descripcion = txtDescripcion.getText();
        //int pos=cmbAbogados.getSelectedIndex();
        //Usuario usuario=(Usuario)cmbAbogados.getSelectedItem();
        //String dni=usuario.getDni();
        if (codigo.isBlank()) {
            JOptionPane.showMessageDialog(this, "Código no puede estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
            txtCodigo.requestFocus();
        } else {
            if (operaciones.existeCodigoCaso(codigo)) {
                JOptionPane.showMessageDialog(this, "Código existente", "Error", JOptionPane.ERROR_MESSAGE);
                txtCodigo.requestFocus();
            } else {
                if (titulo.isBlank()) {
                    JOptionPane.showMessageDialog(this, "Titulo no puede estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
                    txtTitulo.requestFocus();
                } else {
                    if (descripcion.isBlank()) {
                        JOptionPane.showMessageDialog(this, "Debe escribir una descripción", "Error", JOptionPane.ERROR_MESSAGE);
                        txtDescripcion.requestFocus();
                    } else {

                        if (cmbAbogados.getSelectedIndex() == 0) {
                            JOptionPane.showMessageDialog(this, "Seleccione un abogado", "Error", JOptionPane.ERROR_MESSAGE);
                        } else {
                            Usuario usuario = (Usuario) cmbAbogados.getSelectedItem();
                            dni = usuario.getDni();
                            operaciones.crearCaso(codigo, dni, titulo, descripcion, situacion);
                            String codAccion = "APE";
                            String fecha = Fecha.fechaActualNumero();
                            String descripcionAccion = "Apertura del caso";
                            operaciones.crearAccion(codigo, codAccion, fecha, descripcionAccion);
                            JOptionPane.showMessageDialog(this, "Caso creado", "Información", JOptionPane.INFORMATION_MESSAGE);
                            limpiar();
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_btnAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cmbAbogados;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
