/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import baseDatos.Conexion;
import baseDatos.OperacionesTabla;
import javax.swing.JOptionPane;
import modelo.Usuario;

/**
 *
 * @author Yesica
 */
public class VtnOperaciones extends javax.swing.JFrame {

    Conexion conexion;
    OperacionesTabla operaciones;
    Usuario usuario;
    PnlCierreCaso pnlCierreCaso;
    PnlConsultaCasosAbogado pnlConsultaCasosAbogado;
    PnlConsultaCasosAsignados pnlConsultaCasosAsignados;
    PnlNuevasAcciones pnlNuevasAcciones;
    PnlNuevosCasos pnlNuevosCasos;

    /**
     * Creates new form VtnOperaciones
     */
    public VtnOperaciones(String login) {
        initComponents();
        setTitle("Bienvenido " + login);
        conexion = new Conexion();
        if (conexion.establecer("jdbc:mysql://localhost:3306/bufetemachor") == -1) {
            JOptionPane.showMessageDialog(null, "Errores en la base de datos");
            System.exit(-1);
        } else {
            operaciones = new OperacionesTabla(conexion);
        }

        usuario = operaciones.buscarUsuario(login);
        int perfil = usuario.getPerfil();
        if (perfil == 0) {
            mnuNuevosCasos.setVisible(false);
            mnuCierreCasos.setVisible(false);
            mnuConsultaCasosAbogado.setVisible(false);
            mnuConsultaCasosAsignados.setVisible(true);
            mnuNuevasAcciones.setVisible(true);
        } else {
            mnuNuevosCasos.setVisible(true);
            mnuCierreCasos.setVisible(true);
            mnuConsultaCasosAbogado.setVisible(true);
            mnuConsultaCasosAsignados.setVisible(false);
            mnuNuevasAcciones.setVisible(false);
        }

    }

    private void quitarPaneles() {
        fondo.setVisible(false);
        try {
            this.getContentPane().remove(pnlCierreCaso);
        } catch (Exception ex) {
        }
        try {
            this.getContentPane().remove(pnlConsultaCasosAbogado);
        } catch (Exception ex) {
        }
        try {
            this.getContentPane().remove(pnlConsultaCasosAsignados);
        } catch (Exception ex) {
        }
        try {
            this.getContentPane().remove(pnlNuevasAcciones);
        } catch (Exception ex) {
        }
        try {
            this.getContentPane().remove(pnlNuevosCasos);
        } catch (Exception ex) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuConsultaCasosAsignados = new javax.swing.JMenuItem();
        mnuNuevasAcciones = new javax.swing.JMenuItem();
        mnuConsultaCasosAbogado = new javax.swing.JMenuItem();
        mnuNuevosCasos = new javax.swing.JMenuItem();
        mnuCierreCasos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuSalir = new javax.swing.JMenuItem();
        mnuDesconectar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/operaciones.png"))); // NOI18N
        getContentPane().add(fondo);

        jMenu1.setText("Gestión");

        mnuConsultaCasosAsignados.setText("Consulta casos asignados");
        mnuConsultaCasosAsignados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsultaCasosAsignadosActionPerformed(evt);
            }
        });
        jMenu1.add(mnuConsultaCasosAsignados);

        mnuNuevasAcciones.setText("Nuevas acciones");
        mnuNuevasAcciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNuevasAccionesActionPerformed(evt);
            }
        });
        jMenu1.add(mnuNuevasAcciones);

        mnuConsultaCasosAbogado.setText("Consulta casos");
        mnuConsultaCasosAbogado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsultaCasosAbogadoActionPerformed(evt);
            }
        });
        jMenu1.add(mnuConsultaCasosAbogado);

        mnuNuevosCasos.setText("Nuevos casos");
        mnuNuevosCasos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNuevosCasosActionPerformed(evt);
            }
        });
        jMenu1.add(mnuNuevosCasos);

        mnuCierreCasos.setText("Cierre casos");
        mnuCierreCasos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCierreCasosActionPerformed(evt);
            }
        });
        jMenu1.add(mnuCierreCasos);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");

        mnuSalir.setText("Cerrar programa");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        jMenu2.add(mnuSalir);

        mnuDesconectar.setText("Desconectar");
        mnuDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDesconectarActionPerformed(evt);
            }
        });
        jMenu2.add(mnuDesconectar);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        dispose();
        System.exit(0);
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDesconectarActionPerformed
        new VtnLogin().setVisible(true);
        dispose();
        pack();
    }//GEN-LAST:event_mnuDesconectarActionPerformed

    private void mnuConsultaCasosAsignadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsultaCasosAsignadosActionPerformed
        quitarPaneles();
        pnlConsultaCasosAsignados = new PnlConsultaCasosAsignados(usuario);
        this.getContentPane().add(pnlConsultaCasosAsignados);
        pack();
    }//GEN-LAST:event_mnuConsultaCasosAsignadosActionPerformed

    private void mnuNuevasAccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNuevasAccionesActionPerformed
        quitarPaneles();
        pnlNuevasAcciones = new PnlNuevasAcciones(usuario);
        this.getContentPane().add(pnlNuevasAcciones);
        pack();
    }//GEN-LAST:event_mnuNuevasAccionesActionPerformed

    private void mnuConsultaCasosAbogadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsultaCasosAbogadoActionPerformed
        quitarPaneles();
        pnlConsultaCasosAbogado = new PnlConsultaCasosAbogado();
        this.getContentPane().add(pnlConsultaCasosAbogado);
        pack();
    }//GEN-LAST:event_mnuConsultaCasosAbogadoActionPerformed

    private void mnuNuevosCasosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNuevosCasosActionPerformed
        quitarPaneles();
        pnlNuevosCasos = new PnlNuevosCasos();
        this.getContentPane().add(pnlNuevosCasos);
        pack();
    }//GEN-LAST:event_mnuNuevosCasosActionPerformed

    private void mnuCierreCasosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCierreCasosActionPerformed
        quitarPaneles();
        pnlCierreCaso = new PnlCierreCaso();
        this.getContentPane().add(pnlCierreCaso);
        pack();
    }//GEN-LAST:event_mnuCierreCasosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem mnuCierreCasos;
    private javax.swing.JMenuItem mnuConsultaCasosAbogado;
    private javax.swing.JMenuItem mnuConsultaCasosAsignados;
    private javax.swing.JMenuItem mnuDesconectar;
    private javax.swing.JMenuItem mnuNuevasAcciones;
    private javax.swing.JMenuItem mnuNuevosCasos;
    private javax.swing.JMenuItem mnuSalir;
    // End of variables declaration//GEN-END:variables
}
